from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, TextIO
from area_reader_v2 import runner as area_reader_runner
from area_reader_v2.command_group_recommendations import documentation_only_command_groups, is_documentation_only_scope
from automation.model_output_sanitizer import sanitize_model_output
from automation.model_providers import (
    ModelConfig,
    ModelProvider,
    ProviderError,
    create_provider,
    load_provider_config,
    ollama_command_for_model,
    resolve_model_config,
)
from automation.issue_runner_commands import (
    run_command,
)
from automation.issue_runner_contract import (
    RunnerError,
)
from automation.issue_runner_storage import (
    read_optional_text,
    write_text,
)

def create_draft_pr(
    repo: Path,
    github_repo: str,
    issue: int,
    issue_text: str,
    out_dir: Path,
    reader_config: ModelConfig,
    coder_config: ModelConfig,
    stream: TextIO,
) -> str:
    current_branch = run_command(["git", "branch", "--show-current"], cwd=repo, stream=stream).stdout.strip()
    if current_branch in {"main", "master"}:
        raise RunnerError("Refusing to create a PR from the main branch.", 2)
    changed_paths = changed_worktree_paths(repo, stream)
    run_artifacts = [path for path in changed_paths if is_relative_to(repo / path, out_dir)]
    if run_artifacts:
        raise RunnerError("Refusing pr mode because --out files would be committed: " + ", ".join(run_artifacts), 2)
    if not changed_paths:
        raise RunnerError("No changes detected for PR mode after verification.", 2)
    run_command(["git", "add", "--", *changed_paths], cwd=repo, stream=stream)
    run_command(["git", "commit", "-m", f"Implement issue {issue} with AutoDev runner"], cwd=repo, stream=stream)
    run_command(["git", "push", "-u", "origin", current_branch], cwd=repo, stream=stream)
    body_path = out_dir / "draft-pr-body.md"
    body = build_pr_body(issue, issue_text, out_dir, reader_config, coder_config)
    write_text(body_path, body)
    title = first_issue_title(issue_text) or f"Issue #{issue}"
    result = run_command(
        [
            "gh",
            "pr",
            "create",
            "--repo",
            github_repo,
            "--draft",
            "--title",
            title,
            "--body-file",
            str(body_path),
            "--base",
            "main",
            "--head",
            current_branch,
        ],
        cwd=repo,
        stream=stream,
    )
    return "Draft PR created:\n\n" + result.stdout.strip() + "\n"

def changed_worktree_paths(repo: Path, stream: TextIO) -> list[str]:
    result = run_command(["git", "status", "--porcelain"], cwd=repo, stream=stream)
    paths = []
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        path = line[3:].strip()
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        paths.append(path)
    return paths

def is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False

def build_pr_body(
    issue: int,
    issue_text: str,
    out_dir: Path,
    reader_config: ModelConfig,
    coder_config: ModelConfig,
) -> str:
    return "\n".join(
        [
            f"Closes #{issue}",
            "",
            "Generated by AutoDev.",
            "",
            "## Summary",
            "",
            read_optional_text(out_dir / "coder-plan.md").strip() or "See implementation diff.",
            "",
            "## Verification",
            "",
            read_optional_text(out_dir / "verification-result-summary.md").strip(),
            "",
            "## Provider Metadata",
            "",
            "```json",
            json.dumps(
                {"reader": reader_config.safe_metadata(), "coder": coder_config.safe_metadata()},
                indent=2,
                sort_keys=True,
            ),
            "```",
            "",
        ]
    )

def first_issue_title(issue_text: str) -> str:
    for line in issue_text.splitlines():
        if line.startswith("# GitHub Issue") and ":" in line:
            return line.split(":", 1)[1].strip()
    return ""
