name: CI develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-develop-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Integration CI
    uses: ./.github/workflows/ci.yml
    with:
      ref: ${{ github.sha }}
    permissions:
      contents: read
      pull-requests: read
